spring:
    application:
        name: backend

    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: spring.datasource.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
