-- liquibase formatted sql

-- changeset ulise:1746335018374-1
CREATE TABLE "todos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "completed" BOOLEAN NOT NULL, "description" VARCHAR(255), "title" VARCHAR(255), CONSTRAINT "todos_pkey" PRIMARY KEY ("id"));

